version: '3.5'
services:
  scraper:
    build: .
    environment:
      - CONFIG_FILE=/config/config.json
      - DATABASE_PATH=sqlite:////data/exchanges_db.sqlite
    volumes:
      - $PWD/data:/data
      - $PWD/config:/config
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
  metabase-app:
    image: metabase/metabase:v0.43.1
    container_name: metabase
    hostname: metabase
    volumes:
      - /dev/urandom:/dev/random:ro
      - $PWD:/metabase-data
      - $PWD/data:/data
    ports:
      - 3000:3000
    environment:
      MB_DB_FILE: /metabase-data/metabase.db
    networks:
      - metanet1
    depends_on:
      - scraper
networks:
  metanet1:
    driver: bridge